/* generated by info.scce.dime.generator.scheme.ControllerGenerator */
package de.ls5.dywa.generated.controller.dime__HYPHEN_MINUS__models.app;

import de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.ConcreteUser;

public interface ConcreteUserController {

	ConcreteUser read(java.lang.Long id);

	java.util.List<ConcreteUser> findByProperties(ConcreteUser searchObject);

	ConcreteUser findFirstByProperties(ConcreteUser searchObject);

	java.util.Set<ConcreteUser> fetch();

	java.util.Set<ConcreteUser> fetchByName(java.lang.String name);

	ConcreteUser create(java.lang.String name);
	ConcreteUser createTransient(java.lang.String name);

	ConcreteUser createSearchObject(java.lang.String name);

	java.util.Set<ConcreteUser> fetchWithSubtypes();

	void delete(ConcreteUser entity);

	void deleteWithIncomingReferences(ConcreteUser entity);
}
