/* generated by info.scce.dime.generator.scheme.ControllerGenerator */
package de.ls5.dywa.generated.controller.dime__HYPHEN_MINUS__models.app;

import de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.BaseUser;
import de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.BaseUserImpl;
import de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.BaseUserSearch;

import java.util.Arrays;
import java.util.stream.Collectors;

@javax.enterprise.context.RequestScoped
public class BaseUserControllerImpl implements BaseUserController {
	private static final org.slf4j.Logger LOGGER =  org.slf4j.LoggerFactory.getLogger(BaseUserController.class);

	@javax.persistence.PersistenceContext
	private javax.persistence.EntityManager entityManager;

	@javax.inject.Inject
	private de.ls5.dywa.generated.util.DomainFileController domainFileController;

@javax.inject.Inject //referenceMap
private de.ls5.dywa.generated.controller.dime__HYPHEN_MINUS__models.app.ConcreteUserController concreteUserController;

    
    @Override
	public BaseUser read(final java.lang.Long id) {

		 BaseUser result = entityManager.find(BaseUserImpl.class, id);
		 	// delegate read until entity is found;
		return result;
	}

    @Override
	public java.util.List<BaseUser> findByProperties(BaseUser searchObject) {
		if (searchObject instanceof BaseUserSearch) {
			BaseUserSearch casted = (BaseUserSearch) searchObject;

			java.util.List<BaseUser> list = buildSimpleQuery(casted.queryAttributes(), casted.queryListAttributes(), true).getResultList().stream().map(BaseUser::casted).collect(Collectors.toList());

			return list;
		} else {
			throw new java.lang.IllegalArgumentException("Search object required.");
		}
	}

	@Override
	public BaseUser findFirstByProperties(BaseUser searchObject) {
		if (searchObject instanceof BaseUserSearch) {
			BaseUserSearch casted = (BaseUserSearch) searchObject;
			java.util.List<BaseUser> results = new java.util.ArrayList<BaseUser>();
			results.addAll(buildSimpleQuery(casted.queryAttributes(), casted.queryListAttributes(),false).setMaxResults(1).getResultList());
			return results.isEmpty() ? null : results.get(0);
		} else throw new java.lang.IllegalArgumentException("Search object required.");
	}

	@Override
	public java.util.Set<BaseUser> fetch() {
		return new java.util.HashSet<BaseUser>(buildSimpleQuery(null, null,false).getResultList());
	}

	@Override
	public java.util.Set<BaseUser> fetchByName(final java.lang.String name) {
		java.util.Map<String, Object> map = new java.util.HashMap<>();
		map.put("name_", name);
		java.util.HashSet<BaseUser> result = new java.util.HashSet<>(buildSimpleQuery(map, null,false).getResultList());
		return result;
	}

		@Override
		public BaseUser create(java.lang.String name) {
			BaseUserImpl entity = new BaseUserImpl();
			entity.setDywaName(name);
			entityManager.persist(entity);
			return entity;
		}

		@Override
		public BaseUser createTransient(java.lang.String name) {
			BaseUserImpl entity = new BaseUserImpl();
			entity.setDywaName(name);
			return entity;
		}

	@Override
	public BaseUser createSearchObject(java.lang.String name) {
		return new BaseUserSearch(name);
	}

	@Override
	public java.util.Set<BaseUser> fetchWithSubtypes() {
		java.util.Set<BaseUser> list = buildSimpleQuery(null,null, true).getResultList().stream().map(BaseUser::casted).collect(Collectors.toSet());

		return list;
	}

	@Override
	public void delete(BaseUser entity) {

		if (entity instanceof BaseUserImpl) {
			BaseUserImpl impl = (BaseUserImpl) entity;
			{
				de.ls5.dywa.generated.util.FileReference ref = entity.getimage();
				if (ref != null) {
					entity.setimage(null);
					domainFileController.deleteFile(ref);
				}
			}
			entityManager.remove(impl);
		}
		// delegate delete
	}
	
	@Override
	public void deleteWithIncomingReferences(BaseUser entityToDelete) {

		
		// Delete references from type ConcreteUser
			de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.ConcreteUser searchConcreteUser;
			searchConcreteUser = new de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.ConcreteUserSearch();	
				searchConcreteUser.setbaseUser(entityToDelete);
			for (de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.ConcreteUser queryResult : this.concreteUserController.findByProperties(searchConcreteUser)) {
				queryResult.setbaseUser(null);
			}
		delete(entityToDelete);
	}
	
	private javax.persistence.TypedQuery<BaseUserImpl> buildSimpleQuery(java.util.Map<String, Object> attributeMap, java.util.Map<String, java.util.List> listAttributeMap, boolean withInherited) {
		java.lang.StringBuilder queryStr = new java.lang.StringBuilder("SELECT e FROM BaseUserImpl e WHERE (true="+withInherited+" OR e.inheritance_ = false)");
		if (attributeMap != null) {
			for (java.util.Map.Entry<String, Object> entry : attributeMap.entrySet()) {
				queryStr.append(" AND e." + entry.getKey() + " = :" + entry.getKey().replaceAll("\\W", ""));
			}
		}
		if (listAttributeMap != null) {
			for (java.util.Map.Entry<String, java.util.List> entry : listAttributeMap.entrySet()) {
				if (entry.getValue() == null || entry.getValue().isEmpty()) {
					queryStr.append(" AND e." + entry.getKey() + " IS EMPTY");
				} else {
					String prefix = entry.getKey().replaceAll("\\W", "");
					for (int i = 0, s = entry.getValue().size(); i < s; i++) {
						queryStr.append(" AND :" + prefix + i + " MEMBER OF e." + entry.getKey());
					}
				}
			}
		}
		queryStr.append(" ORDER BY id_ DESC");
		javax.persistence.TypedQuery<BaseUserImpl> query = entityManager.createQuery(queryStr.toString(), BaseUserImpl.class);
		if (attributeMap != null) {
			for (java.util.Map.Entry<String, Object> entry : attributeMap.entrySet()) {
				query.setParameter(entry.getKey().replaceAll("\\W", ""), entry.getValue());
			}
		}
		if (listAttributeMap != null) {
			for (java.util.Map.Entry<String, java.util.List> entry : listAttributeMap.entrySet()) {
				if (entry.getValue() != null && !entry.getValue().isEmpty()) {
					String prefix = entry.getKey().replaceAll("\\W", "");
					for (int i = 0, s = entry.getValue().size(); i < s; i++) {
						query.setParameter(prefix + i, entry.getValue().get(i));
					}
				}
			}
		}
		query.setHint(org.hibernate.jpa.QueryHints.HINT_CACHEABLE,true);
		return query;
	}
}
