package info.scce.dime.process.dime__HYPHEN_MINUS__models.interactable;

import javax.annotation.PostConstruct;
import javax.ejb.DependsOn;
import javax.ejb.Singleton;
import javax.ejb.Startup;
import javax.inject.Inject;

/**
 * Generated by startup process generator.
 */
@Singleton
@Startup
@DependsOn("EnumMigrator")
public class StartupStartup {
	
	@Inject
	private info.scce.dime.process.dime__HYPHEN_MINUS__models.interactable.Startup_sA1GYNviEeWsF7MALrkAZQ startupProcess;
	
	@PostConstruct
	public void startup() {
		startupProcess.execute(false);
	}
}
