// generated by SelectiveGenerator#generate(ComplexTypeView view)
package de.ls5.dywa.generated.rest.types;

public class PrivateHomeBaseUserSelectivex1x1x1_NGHA8F4TEear0NzybbrMtw {

	public static void copy(
		final de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.BaseUser from,
		final de.ls5.dywa.generated.rest.types.BaseUser to,
		final info.scce.dime.rest.ObjectCache objectCache) {
	
	
	
		if (objectCache.containsSelective(to, "PrivateHomeBaseUserSelectivex1x1x1_NGHA8F4TEear0NzybbrMtw")) {
			return;
		}
	
		to.setDywaId(from.getDywaId());
		to.setDywaVersion(from.getDywaVersion());
		to.setDywaName(from.getDywaName());
	
		// put to cache, after id has been set
		objectCache.putSelective(to, "PrivateHomeBaseUserSelectivex1x1x1_NGHA8F4TEear0NzybbrMtw");
	
		{
			final de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.BaseUser effectiveFrom = from;
			final de.ls5.dywa.generated.rest.types.BaseUser effectiveTo = to;
		effectiveTo.setlastName(effectiveFrom.getlastName());
		}
		{
			final de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.BaseUser effectiveFrom = from;
			final de.ls5.dywa.generated.rest.types.BaseUser effectiveTo = to;
		effectiveTo.setfirstName(effectiveFrom.getfirstName());
		}
	}
}
