// generated by info.scce.dime.generator.process.BackendProcessGeneratorHelper#generateJSONToContextTransformer
package info.scce.dime.process;

import java.util.List;
import java.util.stream.Collectors;
import javax.inject.Inject;

/**
 * Utility class to explicitly declare the required controllers that need to be injected.
 * This allows to resolve all injection points once at deploy time instead dynamically on each invocation, thus improving performance.
 */
public final class ContextTransformer {

private static ContextTransformer instance;

public static ContextTransformer getInstance(javax.enterprise.inject.spi.BeanManager bm) {
	if (instance == null) {
		instance = info.scce.dime.util.CDIUtil.getManagedInstance(bm, ContextTransformer.class);
	}
	return instance;
}


@Inject de.ls5.dywa.generated.controller.dime__HYPHEN_MINUS__models.app.ConcreteUserController ConcreteUserController;
@Inject de.ls5.dywa.generated.rest.controller.ConcreteUserREST ConcreteUserREST;
@Inject de.ls5.dywa.generated.controller.dime__HYPHEN_MINUS__models.app.BaseUserController BaseUserController;
@Inject de.ls5.dywa.generated.rest.controller.BaseUserREST BaseUserREST;

@Inject de.ls5.dywa.generated.util.DomainFileController domainFileController;

public de.ls5.dywa.generated.util.FileReference transformFile(long dywaId) {
	return domainFileController.getFileReference(dywaId);
}

public de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.ConcreteUser transform(de.ls5.dywa.generated.rest.types.ConcreteUser o) {
	final de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.ConcreteUser obj;
	if (o.getDywaId() > 0) {
		obj = ConcreteUserController.read(o.getDywaId());
	}
	 else if (o instanceof de.ls5.dywa.generated.rest.types.ConcreteUser) {
		obj = ConcreteUserREST.copyToTransient((de.ls5.dywa.generated.rest.types.ConcreteUser) o);
	}
	 else { throw new java.lang.IllegalArgumentException("Unknown type"); } 
	return obj;
}
public de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.BaseUser transform(de.ls5.dywa.generated.rest.types.BaseUser o) {
	final de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.BaseUser obj;
	if (o.getDywaId() > 0) {
		obj = BaseUserController.read(o.getDywaId());
	}
	 else if (o instanceof de.ls5.dywa.generated.rest.types.BaseUser) {
		obj = BaseUserREST.copyToTransient((de.ls5.dywa.generated.rest.types.BaseUser) o);
	}
	 else { throw new java.lang.IllegalArgumentException("Unknown type"); } 
	return obj;
}
}
