package info.scce.dime.process.dime__HYPHEN_MINUS__models.interaction;

import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.Map;
import java.util.Set;
import java.util.stream.Stream;
import java.util.stream.Collectors;
import java.util.Date;
import java.util.UUID;
import java.util.Optional;

import javax.enterprise.inject.spi.BeanManager;
import javax.inject.Inject;

import org.apache.shiro.SecurityUtils;
import org.apache.shiro.subject.Subject;

import info.scce.dime.exception.GUIEncounteredSignal;
import info.scce.dime.exception.GUIEncounteredSignal.GUIInfo;
import info.scce.dime.process.CallFrame;
import info.scce.dime.process.DIMEProcess;
import info.scce.dime.process.DIMEProcessContext;
import info.scce.dime.process.JSONContext;
import info.scce.dime.process.ProcessCallFrame;
import info.scce.dime.util.CDIUtil;

import com.fasterxml.jackson.annotation.JsonAutoDetect;

public final class Home_LWgagF__HYPHEN_MINUS__SEeakMeYoloYxpg implements DIMEProcess {


	// attributes shaping the context variables.
	public static class Context implements DIMEProcessContext {

		// bean manager
		private BeanManager beanManager;
		
		// current eventID
		private String eventId;
		
		// last MajorSIBId
		private String lastMajorSIBId;
		
		// current MajorGUI
		private GUIInfo majorGUIState = null;

		// stack variables
		private ProcessCallFrame callStack = new ProcessCallFrame();


		public info.scce.dime.process.JSONContext toJSON() {
			// this process has no context variables that need to be preserved
			return null;
        }
	}

	private enum SIB_ID {
	___HYPHEN_MINUS__xUtUGUQEea0lrrxwspd7g,
	_3huTEGUQEea0lrrxwspd7g,
		;
	}

	private final BeanManager beanManager;

	@Inject
	public Home_LWgagF__HYPHEN_MINUS__SEeakMeYoloYxpg(final BeanManager beanManager) {
		this.beanManager = beanManager;
	}

	private Context createContext() {
		final Context ctx = new Context();
		ctx.beanManager = this.beanManager;

		// store inputs
		
		return ctx;
	}

	public Home_LWgagF__HYPHEN_MINUS__SEeakMeYoloYxpgResult execute(boolean isAuthenticationRequired) {
		final Context ctx = createContext();
		ctx.callStack.setAuthenticationRequired(isAuthenticationRequired);

		return executeInternal(ctx, SIB_ID.___HYPHEN_MINUS__xUtUGUQEea0lrrxwspd7g);
	}
	
	
	public Home_LWgagF__HYPHEN_MINUS__SEeakMeYoloYxpgResult execute(ProcessCallFrame callStack) {
		final Context ctx = createContext();
		ctx.callStack = callStack;

		return executeInternal(ctx, SIB_ID.___HYPHEN_MINUS__xUtUGUQEea0lrrxwspd7g);
	}

	@Override
	public Home_LWgagF__HYPHEN_MINUS__SEeakMeYoloYxpgResult continueExecution(ProcessCallFrame callStack, info.scce.dime.process.JSONContext context, String sibId, Object slgResult) {
		assert context == null;
		final Context ctx = new Context();
		ctx.beanManager = this.beanManager;
		ctx.callStack = callStack;

		switch (sibId) {
		case "_-xUtUGUQEea0lrrxwspd7g": return executeInternal(ctx, continue___HYPHEN_MINUS__xUtUGUQEea0lrrxwspd7g(ctx, slgResult));
		case "_3huTEGUQEea0lrrxwspd7g": return executeInternal(ctx, continue_3huTEGUQEea0lrrxwspd7g(ctx, slgResult));
			default: throw new IllegalStateException("Unknown continuation point '" + sibId + '\'');
		}
	}

	private Home_LWgagF__HYPHEN_MINUS__SEeakMeYoloYxpgResult executeInternal(final Context ctx, final SIB_ID id) {
		SIB_ID curr = id;
		while (true) {
			switch (curr) {
				case ___HYPHEN_MINUS__xUtUGUQEea0lrrxwspd7g: {
					curr = execute___HYPHEN_MINUS__xUtUGUQEea0lrrxwspd7g(ctx);
					break;
				}
				case _3huTEGUQEea0lrrxwspd7g: {
					curr = execute_3huTEGUQEea0lrrxwspd7g(ctx);
					break;
				}
				default: {
					throw new IllegalStateException("unhandled SIB container " + curr);
				}
			}
		}
	}
	
	/**
	 * The return type for this process. It stores the corresponding branch name 
	 * as well as the corresponding result for the branch.
	 */
	public static class Home_LWgagF__HYPHEN_MINUS__SEeakMeYoloYxpgResult implements info.scce.dime.process.DIMEProcessResult<Void> {
		private String branchName;
		private String branchId;
		
		public String getBranchName() {
			return branchName;
		}
		
		public String getBranchId() {
			return branchId;
		}
		

	}
	
	// model branches.


	// sibs
	// Input class -- generated by info.scce.dime.generator.process.BackendProcessGeneratorHelper#renderInputClass(SIB)
	//   for SIB PublicHome _-xUtUGUQEea0lrrxwspd7g
	private static class InputsForGUISIB___HYPHEN_MINUS__xUtUGUQEea0lrrxwspd7g {
	}
	
	
	// container for GUI SIB 'PublicHome'.
	public SIB_ID execute___HYPHEN_MINUS__xUtUGUQEea0lrrxwspd7g(final Context ctx) {
	
		
		final InputsForGUISIB___HYPHEN_MINUS__xUtUGUQEea0lrrxwspd7g inputs = new InputsForGUISIB___HYPHEN_MINUS__xUtUGUQEea0lrrxwspd7g();
		
		
		final CallFrame currentFrame = new CallFrame("info.scce.dime.process.dime__HYPHEN_MINUS__models.interaction.Home_LWgagF__HYPHEN_MINUS__SEeakMeYoloYxpg:_-xUtUGUQEea0lrrxwspd7g:_LmrS0Ej8EeaK4_MRcoLfnw", ctx, ctx.lastMajorSIBId);
		
		ctx.callStack.getCallFrames().add(currentFrame);
	
		GUIEncounteredSignal signal = new GUIEncounteredSignal(ctx.callStack, "_-xUtUGUQEea0lrrxwspd7g", inputs);
		
		throw signal;
	}
	
	public SIB_ID continue___HYPHEN_MINUS__xUtUGUQEea0lrrxwspd7g(Context ctx, Object guiResult) {
		if(ctx.callStack.isAuthenticationRequired()) {
			final Subject shiroSubj = SecurityUtils.getSubject();
			if (!shiroSubj.isAuthenticated()) {
				GUIEncounteredSignal sig = new GUIEncounteredSignal(ctx.callStack, "_-xUtUGUQEea0lrrxwspd7g");
				sig.setStatus(401);
				throw sig;
			}
		}
		
		ctx.callStack.getCallFrames().remove(ctx.callStack.getCallFrames().size()-1);
		
		final info.scce.dime.gui.dime__HYPHEN_MINUS__models.gui.publichome.PublicHome_LmrS0Ej8EeaK4_MRcoLfnwResult result = (info.scce.dime.gui.dime__HYPHEN_MINUS__models.gui.publichome.PublicHome_LmrS0Ej8EeaK4_MRcoLfnwResult) guiResult;
		if ("Login".equals(result.getBranchName())) {
			// branch 'Login'
			return SIB_ID._3huTEGUQEea0lrrxwspd7g;
		}
		else {
			// unspecified branch, show same GUI again
			return execute___HYPHEN_MINUS__xUtUGUQEea0lrrxwspd7g(ctx);
		}
	}
	// Input class -- generated by info.scce.dime.generator.process.BackendProcessGeneratorHelper#renderInputClass(SIB)
	//   for SIB PrivateHome _3huTEGUQEea0lrrxwspd7g
	private static class InputsForGUISIB_3huTEGUQEea0lrrxwspd7g {
	}
	
	
	// container for GUI SIB 'PrivateHome'.
	public SIB_ID execute_3huTEGUQEea0lrrxwspd7g(final Context ctx) {
	
		
		final InputsForGUISIB_3huTEGUQEea0lrrxwspd7g inputs = new InputsForGUISIB_3huTEGUQEea0lrrxwspd7g();
		
		
		final CallFrame currentFrame = new CallFrame("info.scce.dime.process.dime__HYPHEN_MINUS__models.interaction.Home_LWgagF__HYPHEN_MINUS__SEeakMeYoloYxpg:_3huTEGUQEea0lrrxwspd7g:_NGHA8F4TEear0NzybbrMtw", ctx, ctx.lastMajorSIBId);
		
		ctx.callStack.getCallFrames().add(currentFrame);
	
		GUIEncounteredSignal signal = new GUIEncounteredSignal(ctx.callStack, "_3huTEGUQEea0lrrxwspd7g", inputs);
		
		throw signal;
	}
	
	public SIB_ID continue_3huTEGUQEea0lrrxwspd7g(Context ctx, Object guiResult) {
		if(ctx.callStack.isAuthenticationRequired()) {
			final Subject shiroSubj = SecurityUtils.getSubject();
			if (!shiroSubj.isAuthenticated()) {
				GUIEncounteredSignal sig = new GUIEncounteredSignal(ctx.callStack, "_3huTEGUQEea0lrrxwspd7g");
				sig.setStatus(401);
				throw sig;
			}
		}
		
		ctx.callStack.getCallFrames().remove(ctx.callStack.getCallFrames().size()-1);
		
		// unspecified branch, show same GUI again
		return execute_3huTEGUQEea0lrrxwspd7g(ctx);
	}
	
}  
