// generated by SelectiveGenerator#generate(ComplexTypeView view)
package de.ls5.dywa.generated.rest.types;

public class PrivateHomeConcreteUserSelectivex1_NGHA8F4TEear0NzybbrMtw {

	public static void copy(
		final de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.ConcreteUser from,
		final de.ls5.dywa.generated.rest.types.ConcreteUser to,
		final info.scce.dime.rest.ObjectCache objectCache) {
	
	
	
		if (objectCache.containsSelective(to, "PrivateHomeConcreteUserSelectivex1_NGHA8F4TEear0NzybbrMtw")) {
			return;
		}
	
		to.setDywaId(from.getDywaId());
		to.setDywaVersion(from.getDywaVersion());
		to.setDywaName(from.getDywaName());
	
		// put to cache, after id has been set
		objectCache.putSelective(to, "PrivateHomeConcreteUserSelectivex1_NGHA8F4TEear0NzybbrMtw");
	
		{
			final de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.ConcreteUser effectiveFrom = from;
			final de.ls5.dywa.generated.rest.types.ConcreteUser effectiveTo = to;
		final de.ls5.dywa.generated.entity.dime__HYPHEN_MINUS__models.app.BaseUser
		 source = effectiveFrom.getbaseUser();
		if (source != null) {
			// original selective: PrivateHomeBaseUserSelectivex1x1x1_NGHA8F4TEear0NzybbrMtw
			de.ls5.dywa.generated.rest.types.BaseUser cached = objectCache.getRestTo(source);
			
			if (cached == null) {
				cached = de.ls5.dywa.generated.rest.types.BaseUser.fromDywaEntity(source, objectCache);
			}
			
			if (!objectCache.containsSelective(cached, "PrivateHomeBaseUserSelectivex1x1x1_NGHA8F4TEear0NzybbrMtw")) {
				de.ls5.dywa.generated.rest.types.PrivateHomeBaseUserSelectivex1x1x1_NGHA8F4TEear0NzybbrMtw.copy(source, cached, objectCache);
			}
		
			effectiveTo.setbaseUser(cached);
		}
		}
	}
}
