version: '3.7'
services:
  wildfly:
    build:
      context: .
      dockerfile: development.Dockerfile
    depends_on:
      - mailcatcher
      - postgres
    environment:
      DIME_APP_ENCRYPT: 'false'
      DIME_APP_MAIL_PORT: 1025
      DIME_APP_MAIL_SERVER: mailcatcher
      DIME_APP_SERVER_TIER: local
      DIME_APP_SERVER_URL: http://127.0.0.1:8080/
      DIME_APP_CONFIG: '{}'
      DIME_APP_LOG_LEVEL: 'DEBUG'
      DIME_APP_AUTH_PRIVATE_KEY: 'MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDOyw1U7Wx9ZVwb9rVE7wuSgPCa5EUEhe7kqjq7U93yucNzhpth8svz5DgK62iUqEpOcLMO8L+UzZ5XfFHj6+NbYhSTN8LhhhCSuUg6+rXnBPURkwkgFVXVyTLmlF8e+KYCEo4WsqmFxi+wgDJ4L+kXyyO10tn0sDW0PVgm0lGO83PX7DRNufUeZe9aGIYAj2IawMGoq9AhdYHrIP9yy/+5VYJyOUpU07Ju7nudajpOGc9hb4nYYu/Y2ruHdNMZ6ctbQN75kkQ7dH/umRSVUGlN/Nv1+65/OZFuKBf4CtzbBrcUtRZ9A3FnLbyG45lAzXv10GwuL2+QpXmLIHF2PYQfAgMBAAECggEBAIChsdNINJnzuM30MmGEyJADAKd4oq3jmexHL21jB8Z6YuezrWfKHa/CIFI6iL0fycjtNZRvkNxA4uPMgyvhiXVIlz/UCbc7K4f5FMMLPKdNYBvkeGKqos/u7WiclmaviKP1YskfrW93DiceN0anlrikNbxeQhGAoodROUo8vVrLWVUAtgnN/hb8M7bmgriOrinPGzKbNjS1N4KXiUiXjB4eOQjotxIxndD52UZQh50jFvLjaCcqw7+0AaWglz5xh+h3mUvet7996dRFZ0ag80eOCbLr6vwKhAfmHCl/MkUkAeC9fOrNJYT0LoOdS70nCjaenusSJRDZwu68RXXw50ECgYEA/znktRLiNl0ZA/G16G+G424Kf9IeQEfYWk8O3sMtUBFK9OFm7OFRKZXdrdHZsITlgNw7RyytNNvyPkkbQzEDfmwNm5TNmlj6CSMgbzWD+JAwMj22xh3ll4COvO/eeIWIIxf+9Jf9ySgfpB09yCB/bpZZwp2CPqjk50qORl909m8CgYEAz2uQo9menNnTyp7d6hJ80PYaAsdaejXnlLPaFomCWPXbj4sCHcgOWMEA9v1AS86WgkDD6Mdl1XKkbvc5V3LJDBoxyGB10UuHLbKLpr408s3kd8b6jmERQoTz2KeFBpNF1ynELRIcOX8ChNPTqb/X2KmyiU1AItuG0vsPKLn6pVECgYEArzVRGjUycduLVrfSBxS45twd/Q2DkuE/Vw+6x5X5P2P/rwglniw3iXLGUZMj/BffbYzCbOPwq77qF3QccQ3uthT7anjGhFTcoPUqSO3WAQcK7xKKrIrNmCm6011fviD9CgppDgRhRnxy7DjetsoIcSRpzj5OsTFEorr93LWfF6UCgYAzHegkaSIst4X5XlOENxApkyzv2F9U1OoAfJ5XhYXpFJYKdxCLdF0MxGvPcrQguoXfDcT6HgHbq4gYjLbF9VTUtbPlFNiUPs/OlDzUV/XGjLUsS449/m/5e7h4gThIWY0RrIpbLSZliQZ+45E7OTshexizu6T9sio03ohq2gKKMQKBgQDljG/GI+HZsEZ5BqA4RDx3+WscrpEL4keMOnr7i4eoGG7bwb0jcdQjczDJh6Nn+fSZPVOJ90zb8NGpZPSktuotDETXDWRJgeWuEbs298hjeWc9nwrgCBTPaS5ZaqF8SA4Svwr2MfeEki4GtkCmBtdSGgHvOgkzovK/zRJU6WtTFw=='
      DIME_APP_AUTH_PUBLIC_KEY: 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzssNVO1sfWVcG/a1RO8LkoDwmuRFBIXu5Ko6u1Pd8rnDc4abYfLL8+Q4CutolKhKTnCzDvC/lM2eV3xR4+vjW2IUkzfC4YYQkrlIOvq15wT1EZMJIBVV1cky5pRfHvimAhKOFrKphcYvsIAyeC/pF8sjtdLZ9LA1tD1YJtJRjvNz1+w0Tbn1HmXvWhiGAI9iGsDBqKvQIXWB6yD/csv/uVWCcjlKVNOybu57nWo6ThnPYW+J2GLv2Nq7h3TTGenLW0De+ZJEO3R/7pkUlVBpTfzb9fuufzmRbigX+Arc2wa3FLUWfQNxZy28huOZQM179dBsLi9vkKV5iyBxdj2EHwIDAQAB'
      DATASOURCE_SERVER_NAME: postgres
      DATASOURCE_DATABASE_NAME: dywa
      DATASOURCE_USER: sa
      DATASOURCE_PASSWORD: sa
      ALLOWED_ORIGINS: '*'
      JAVA_OPTS: -Xms64m -Xmx2g -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=512m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - dywaapp:/opt/jboss/wildfly/standalone/data/files
  postgres:
    image: registry.gitlab.com/scce/docker-images/postgres-dime:9.5.4
    environment:
      POSTGRES_DB: dywa
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
  mailcatcher:
    image: registry.gitlab.com/scce/docker-images/mailcatcher:0.7.1
    ports:
      - 127.0.0.1:8888:1080
volumes:
  postgres:
  dywaapp:
